li=input("enter elements of list 1(seperated by space)-")
list1=li.split()
print(list1)
l2=input("enter elements of list 2(seperated by space)-")
list2=l2.split()
print(list2)
print("list1 + list2-",list1+list2)